name: Generate Snake

on:
  # Tự động chạy mỗi 24 giờ
  schedule:
    - cron: "0 */24 * * *"

  # Cho phép chạy thủ công bất cứ lúc nào
  workflow_dispatch:

  # Chạy mỗi khi bạn push code lên branch main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Tạo hoạt ảnh rắn từ đóng góp của VN-PhanQuocBinh
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: VN-PhanQuocBinh
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Đẩy file đã tạo lên nhánh 'output' để README có thể truy cập
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
